#!/usr/bin/env bash
# commerce-work-sync.sh [--dry-run]
#
# Refresh the WRITABLE working copy of the Acropora Commerce stage project.
#
# Why a copy at all: /opt/acropora-commerce-stage is bind-mounted READ-ONLY into
# this container (approved 2026-08-22), so the agent cannot create source files
# there. The copy is a snapshot: it does not follow later changes on stage, and
# nothing here is ever written back.
#
# The exclusion list is the whole point of this script:
#   - `.env*` never leaves the stage tree (DB and service secrets)
#   - `apps/backend/.medusa` is BUILD OUTPUT, regenerated by `medusa build`
#   - `node_modules/**/.medusa` must be COPIED: for at least one package
#     (@medusajs/draft-order) that directory holds the entire published code
#     (`files: [".medusa/server"]`), so skipping it leaves an empty shell and the
#     build dies on a missing entry point.
#
# Measured 2026-08-22: the first copy excluded `.medusa` BY NAME, which took the
# draft-order package's real code with it. Bind the pattern to the PATH, not the
# name -- otherwise the same failure returns later, in another package, when the
# cause is no longer obvious.
#
#   bash /home/marveen/marveen/scripts/commerce-work-sync.sh --dry-run
#   bash /home/marveen/marveen/scripts/commerce-work-sync.sh

set -uo pipefail

DRY=0
for a in "$@"; do
  case "$a" in
    --dry-run) DRY=1 ;;
    *) echo "commerce-work-sync.sh: unknown flag $a" >&2; exit 2 ;;
  esac
done

SRC=/opt/acropora-commerce-stage/backend
DEST=/home/marveen/marveen/agents/nautilus/commerce-work

[[ -d "$SRC" ]] || { echo "FAIL: $SRC is not mounted (compose volume missing?)" >&2; exit 1; }

# The two exclusions need OPPOSITE shapes, and mixing them up breaks something
# either way (Medusa's point, 2026-08-22, and it caught a real bug in this file):
#   - `.medusa` must be PATH-anchored. Name-wide, it also removes the published
#     code of packages that ship under `.medusa/server`, and the build dies.
#   - `.env*` must be NAME-wide, at any depth. Path-anchored to the root it lets
#     `apps/backend/.env` -- the real stage secret file -- into the copy.
#     Measured: with the anchored form, tar listed apps/backend/.env.
# So: too broad breaks the build, too narrow leaks a secret. Do not "make them
# consistent"; they are deliberately different.
EXCLUDES=(
  --exclude='.env'
  --exclude='.env.*'
  --exclude='./apps/backend/.medusa'
)

if (( DRY )); then
  echo "source:      $SRC"
  echo "destination: $DEST"
  echo "excludes:    ${EXCLUDES[*]}"
  echo
  echo "-- what the pattern does to the two .medusa directories --"
  ( cd "$SRC" && tar cf /dev/null "${EXCLUDES[@]}" -v . 2>/dev/null \
      | grep -E '\.medusa' | head -5 ) || true
  echo "(the lines above are COPIED; apps/backend/.medusa must not appear)"
  exit 0
fi

mkdir -p "$DEST" || exit 1
( cd "$SRC" && tar cf - "${EXCLUDES[@]}" . ) | ( cd "$DEST" && tar xf - ) || {
  echo "FAIL: copy did not complete" >&2; exit 1; }

echo "-- verify --"
du -sh "$DEST"
echo -n "draft-order package code present: "
[[ -d "$DEST/node_modules/@medusajs/draft-order/.medusa/server" ]] && echo YES || echo "NO -- the build will fail"
echo -n "build output excluded: "
[[ -d "$DEST/apps/backend/.medusa" ]] && echo "no (present, harmless but stale)" || echo yes
echo -n "secrets excluded: "
[[ -z "$(find "$DEST" -maxdepth 2 -name '.env*' -print -quit)" ]] && echo yes || echo "NO -- remove them"
